apiVersion: external-secrets.io/v1beta1
kind: ExternamSecretStore 
metadata: 
  name : {{ .values.app.name }}  
  namesapce: {{ .values.namespaces }} 
spec: 
  refreshInterval: 1h 
  secreatStoreRef: 
    name: {{ .values.secretStore.name }} 
  target:
    name: {{ .values.externamSecret.secretKey }}  
    creattionPolicy: Owner
    data: 
     - secretKey: DB_USERNAME 
       remoteRef: 
        key: db-secret 
        property: username 
     - secretKey: DB_PASSWORD 
       remoteRef: 
         key: db-secret 
         property: password 
