apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata: 
  name: {{ .values.secretStore.name }} 
  namesapce: {{ .values.namespaces }} 
spec:
  provider:   
    aws: 
      service: SecreatManger 
      region: {{ .values.secretStore.region }} 
      auth: 
        jwt: 
          serviceAccounrRef: 
            name: {{.value.secretStore.serviceAccountName }} 