import yaml

DEPLOYMENT_FILE = "deployment.yaml"
CONTAINER_NAME = "my-app"     # change if needed
NEW_IMAGE = "nginx:1.25.4"    # new version

def update_image_version(file_path):
    with open(file_path, "r") as f:
        docs = list(yaml.safe_load_all(f))

    for doc in docs:
        if doc.get("kind") == "Deployment":
            containers = (
                doc["spec"]
                ["template"]
                ["spec"]
                ["containers"]
            )

            for container in containers:
                if container["name"] == CONTAINER_NAME:
                    old_image = container["image"]
                    container["image"] = NEW_IMAGE
                    print(f"Updated image: {old_image} → {NEW_IMAGE}")

    with open(file_path, "w") as f:
        yaml.safe_dump_all(docs, f, sort_keys=False)

if __name__ == "__main__":
    update_image_version(DEPLOYMENT_FILE)


with open('file_path', 'r') os f: 
   docs = list 



