# scereat store 
# user aws secretManger to manage the secreats and use externam secreat store to sync the secreats to k8s cluster
# 1 creare secret manger in aws 
# 2 create IAM policy 
# 3 create iam role and attach this policy to the role
# 4 install externam secret operater 
# 5 create secret store (connect to aws) 
# 6 create externam secret store to fatch secret from secret amanger automatically 
# 7 verify secret manget using kubectl get secret my-db-secret -o yaml 
# 8 use this secret in deployment
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata: 
  name: aws-secreat-store 
  namesapce: default 
spec:
  provider:   
    aws: 
      service: SecreatManger 
      region: us-east-1
      auth: 
        jwt: 
          serviceAccounrRef: 
            name: aws-secreat-store-sa 
# externam secreat store 

apiVersion: external-secrets.io/v1beta1
kind: ExternamSecretStore 
metadata: 
  name : my-db-secret 
  namesapce: default 
spec: 
  refreshInterval: 1h 
  secreatStoreRef: 
    nsme: aws-secreat-store
  target:
    name: my-db-secret 
    creattionPolicy: Owner
    data: 
     - secretKey: DB_USERNAME 
       remoteRef: 
        key: db-secret 
        property: username 
     - secretKey: DB_PASSWORD 
       remoteRef: 
         key: db-secret 
         property: password 

# deployment 

aviVersion: apps/v1 
kind: Depoyment 
metadata: 
  name: my-app 
  namespace: default 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: my-app 
  template: 
    metadata: 
      labels: 
        app:my-app 
    spec: 
      containers: 
        - name: my-app 
        image: my-repo/my-image:latest
        ports: 
          - containerPort: 8080 
        env: 
          - name: DB_USERNAME 
            valueFrom: 
              keyRef: 
                name: db-secret 
                key: username         
# service

apiVersion: v1 
kind: Service
metadata: 
  name: my-app-svc 
  nameSpace: default 
spec: 
  selector: 
    app: my-app 
  ports: 
    - protical: TCP 
      port: 80 
      targetPort: 8080 
      type: LoadBlancer 


# ingresss

apiVersion: networking.k8s.io/v1
kind: Ingresss 
metadata: 
  name: my-app-ingress 
  namespace: default 
spec: 
  rules: 
   - host: my-app.example.com 
     http: 
       paths:
         servcie: 
           name: my-app-sec 
           paths: 
             path: / 
               type: Prefix 
                 ports: 
                   number: 80   
# persistanceVolume

apiVersion: v1 
kind: PersistanceVolume 
metadata: 
  name: mysql-pv 
spec: 
  capacity: 
    storage: 5Gi 
  accessMode: 
   - ReadWriteOnceOnce 
  hostPath: 
    path: /data/mysq 

# persistanceVolumeClaim

apiVersion: v1
kind: PersistanceVolumeClaim
metadata: 
  namme: muysql-pvc 
spec: 
  accessMode: 
    - ReadWriteOnce
  resource: 
    request: 
      storage: 5Gi

# mysql statefulset depoymet 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: three-tier
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi




  
   
   